# Generated by Django 5.1.2 on 2024-10-19 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField()),
                ('predicted_close_price', models.FloatField()),
            ],
        ),
        migrations.AddIndex(
            model_name='stockdata',
            index=models.Index(fields=['date', 'symbol'], name='stocks_stoc_date_be36f4_idx'),
        ),
        migrations.AddField(
            model_name='stockprediction',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='stocks.stockdata'),
        ),
    ]
